export const defaultChecklistItems = [
  { code: "1-1", category: "배차 및 차량 등록", content: "어린이통학버스 신고 여부", sortOrder: 1 },
  { code: "1-2", category: "배차 및 차량 등록", content: "신고필증 차량 내 부착 여부", sortOrder: 2 },
  { code: "1-3", category: "배차 및 차량 등록", content: "정기검사 합격 여부", sortOrder: 3 },
  { code: "2-1", category: "운전자", content: "신규 안전교육 이수 여부", sortOrder: 4 },
  { code: "2-2", category: "운전자", content: "정기 안전교육 이수 여부", sortOrder: 5 },
  { code: "2-3", category: "운전자", content: "안전교육 수료증 비치 여부", sortOrder: 6 },
  { code: "2-4", category: "운전자", content: "안전운행기록 제출 여부", sortOrder: 7 },
  { code: "3-1", category: "동승자", content: "신규 안전교육 이수 여부", sortOrder: 8 },
  { code: "3-2", category: "동승자", content: "정기 안전교육 이수 여부", sortOrder: 9 },
  { code: "4-1", category: "운전자·동승자 의무", content: "운행 전 안전띠 및 좌석 상태 확인", sortOrder: 10 },
  { code: "4-2", category: "운전자·동승자 의무", content: "승차 시 어린이 탑승 확인", sortOrder: 11 },
  { code: "4-3", category: "운전자·동승자 의무", content: "모든 어린이의 안전띠 착용 확인", sortOrder: 12 },
  { code: "4-4", category: "운전자·동승자 의무", content: "하차 시 주변 안전 확인 및 인계", sortOrder: 13 },
  { code: "4-5", category: "운전자·동승자 의무", content: "하차 후 차량 내부 잔류 어린이 확인", sortOrder: 14 },
  { code: "4-6", category: "운전자·동승자 의무", content: "동승보호자 표지 및 안전 장비 확인", sortOrder: 15 },
  { code: "5-1", category: "승·하차 장소 및 사고 대응", content: "안전한 승·하차 장소 지정 여부", sortOrder: 16 },
  { code: "5-2", category: "승·하차 장소 및 사고 대응", content: "승·하차 장소의 안전표지 설치 여부", sortOrder: 17 },
  { code: "5-3", category: "승·하차 장소 및 사고 대응", content: "사고 발생 시 대응 연락망 보유 여부", sortOrder: 18 },
] as const;
