create extension if not exists btree_gist with schema extensions;

create table public.school_settings (
  id smallint primary key check (id = 1),
  school_year integer not null,
  start_date date not null,
  end_date date not null,
  include_labor_day smallint not null default 1 check (include_labor_day in (0, 1)),
  include_election_day smallint not null default 1 check (include_election_day in (0, 1)),
  updated_at timestamptz not null default now()
);

create table public.buses (
  id bigint generated by default as identity primary key,
  bus_number integer not null unique check (bus_number > 0),
  plate_number text,
  driver_name text,
  attendant_name text,
  active smallint not null default 1 check (active in (0, 1))
);

create table public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  grade integer not null check (grade between 1 and 6),
  class_name text not null,
  active smallint not null default 1 check (active in (0, 1))
);

create table public.assignments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  bus_id bigint not null references public.buses(id),
  stop_name text,
  start_date date not null,
  end_date date not null,
  check (start_date <= end_date),
  exclude using gist (
    student_id with =,
    daterange(start_date, end_date, '[]') with &&
  )
);

create table public.calendar_exclusions (
  id bigint generated by default as identity primary key,
  date date not null unique,
  kind text not null check (kind in ('discretionary_holiday', 'emergency', 'other')),
  note text
);

create table public.daily_runs (
  id bigint generated by default as identity primary key,
  bus_id bigint not null references public.buses(id),
  date date not null,
  status text not null check (status in ('operated', 'not_operated')),
  reason text,
  note text,
  unique (bus_id, date)
);

create table public.boarding_records (
  id bigint generated by default as identity primary key,
  daily_run_id bigint not null references public.daily_runs(id) on delete cascade,
  student_id bigint not null references public.students(id),
  boarded smallint not null default 0 check (boarded in (0, 1)),
  note text,
  unique (daily_run_id, student_id)
);

create table public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  display_name text,
  role text not null check (role in ('admin', 'driver', 'attendant')),
  pin_salt text not null,
  pin_hash text not null,
  active smallint not null default 1 check (active in (0, 1))
);

create table public.sessions (
  id text primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table public.login_throttles (
  username text primary key,
  attempt_count integer not null default 0,
  window_started_at timestamptz not null
);

create table public.inspection_groups (
  id bigint generated by default as identity primary key,
  name text not null,
  active smallint not null default 1 check (active in (0, 1))
);

create table public.inspection_group_buses (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.inspection_groups(id) on delete cascade,
  bus_id bigint not null references public.buses(id) on delete cascade,
  unique (group_id, bus_id),
  unique (bus_id)
);

create table public.checklist_items (
  id bigint generated by default as identity primary key,
  code text not null unique,
  category text not null,
  content text not null,
  responsible_role text not null default 'all' check (responsible_role in ('all', 'driver', 'attendant')),
  sort_order integer not null,
  active smallint not null default 1 check (active in (0, 1))
);

create table public.user_bus_assignments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  bus_id bigint not null references public.buses(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  check (start_date <= end_date)
);

create table public.monthly_inspections (
  id bigint generated by default as identity primary key,
  month text not null check (month ~ '^20[0-9]{2}-(0[1-9]|1[0-2])$'),
  group_id bigint not null references public.inspection_groups(id),
  status text not null default 'draft' check (status in ('draft', 'complete', 'submitted')),
  submitted_at timestamptz,
  unique (month, group_id)
);

create table public.monthly_inspection_buses (
  id bigint generated by default as identity primary key,
  inspection_id bigint not null references public.monthly_inspections(id) on delete cascade,
  bus_id bigint not null references public.buses(id),
  unique (inspection_id, bus_id)
);

create table public.inspection_responses (
  id bigint generated by default as identity primary key,
  inspection_id bigint not null references public.monthly_inspections(id) on delete cascade,
  item_code text not null references public.checklist_items(code),
  answer text not null check (answer in ('yes', 'no', 'not_applicable')),
  note text,
  unique (inspection_id, item_code)
);

create index assignments_bus_dates_idx on public.assignments (bus_id, start_date, end_date);
create index daily_runs_date_status_idx on public.daily_runs (date, status);
create index user_bus_assignments_lookup_idx on public.user_bus_assignments (user_id, bus_id, start_date, end_date);
create index inspection_group_buses_group_idx on public.inspection_group_buses (group_id);
create index sessions_expiry_idx on public.sessions (expires_at);

insert into public.buses (bus_number)
select number from generate_series(1, 18) as number;

insert into public.inspection_groups (name)
select number || '세트' from generate_series(1, 9) as number;

insert into public.inspection_group_buses (group_id, bus_id)
select groups.id, buses.id
from public.inspection_groups groups
join public.buses buses on buses.bus_number in (
  ((substring(groups.name from '^[0-9]+'))::integer * 2) - 1,
  ((substring(groups.name from '^[0-9]+'))::integer * 2)
);

insert into public.checklist_items (code, category, content, responsible_role, sort_order) values
  ('1-1', '버스 기본사항', '어린이통학버스 신고 여부', 'all', 1),
  ('1-2', '버스 기본사항', '신고필증 차량 내 부착 여부', 'all', 2),
  ('1-3', '버스 기본사항', '정기검사 합격 여부', 'all', 3),
  ('2-1', '운전자', '신규 안전교육 이수 여부', 'driver', 4),
  ('2-2', '운전자', '정기 안전교육 이수 여부', 'driver', 5),
  ('2-3', '운전자', '안전교육 수료증 비치 여부', 'driver', 6),
  ('2-4', '운전자', '안전운행기록 제출 여부', 'driver', 7),
  ('3-1', '동승자', '신규 안전교육 이수 여부', 'attendant', 8),
  ('3-2', '동승자', '정기 안전교육 이수 여부', 'attendant', 9),
  ('4-1', '운전자·동승자 의무', '운행 전 안전띠 및 좌석 상태 확인', 'all', 10),
  ('4-2', '운전자·동승자 의무', '승차 시 어린이 탑승 확인', 'all', 11),
  ('4-3', '운전자·동승자 의무', '모든 어린이의 안전띠 착용 확인', 'all', 12),
  ('4-4', '운전자·동승자 의무', '하차 시 주변 안전 확인 및 인계', 'all', 13),
  ('4-5', '운전자·동승자 의무', '하차 후 차량 내부 잔류 어린이 확인', 'all', 14),
  ('4-6', '운전자·동승자 의무', '동승보호자 표지 및 안전 장비 확인', 'all', 15),
  ('5-1', '승·하차 장소 및 사고 대응', '안전한 승·하차 장소 지정 여부', 'all', 16),
  ('5-2', '승·하차 장소 및 사고 대응', '승·하차 장소의 안전표지 설치 여부', 'all', 17),
  ('5-3', '승·하차 장소 및 사고 대응', '사고 발생 시 대응 연락망 보유 여부', 'all', 18);

insert into public.school_settings (id, school_year, start_date, end_date)
values (
  1,
  extract(year from current_date)::integer,
  make_date(extract(year from current_date)::integer, 3, 2),
  make_date(extract(year from current_date)::integer + 1, 2, 28)
);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'school_settings', 'buses', 'students', 'assignments', 'calendar_exclusions',
    'daily_runs', 'boarding_records', 'app_users', 'sessions', 'login_throttles',
    'inspection_groups', 'inspection_group_buses', 'checklist_items',
    'user_bus_assignments', 'monthly_inspections', 'monthly_inspection_buses',
    'inspection_responses'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
    execute format('grant select, insert, update, delete on table public.%I to service_role', table_name);
  end loop;
end
$$;

grant usage, select on all sequences in schema public to service_role;
