create table public.user_group_assignments (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete cascade,
  group_id bigint not null references public.inspection_groups(id),
  start_date date not null,
  end_date date not null,
  check (start_date <= end_date),
  unique (user_id)
);

create index user_group_assignments_group_id_idx
  on public.user_group_assignments(group_id);

alter table public.user_group_assignments enable row level security;
revoke all on table public.user_group_assignments from anon, authenticated;
grant select, insert, update, delete on table public.user_group_assignments to service_role;
grant usage, select on sequence public.user_group_assignments_id_seq to service_role;

insert into public.user_group_assignments (user_id, group_id, start_date, end_date)
select user_id, group_id, start_date, end_date
from (
  select distinct on (assignments.user_id)
    assignments.user_id,
    group_buses.group_id,
    min(assignments.start_date) as start_date,
    max(assignments.end_date) as end_date
  from public.user_bus_assignments assignments
  join public.inspection_group_buses group_buses on group_buses.bus_id = assignments.bus_id
  join public.app_users users on users.id = assignments.user_id
  where users.role in ('driver', 'attendant')
  group by assignments.user_id, group_buses.group_id
  order by assignments.user_id, count(*) desc, group_buses.group_id
) migrated
on conflict (user_id) do nothing;

do $$
declare
  operation_user record;
  candidate text;
begin
  for operation_user in
    select id from public.app_users where role in ('driver', 'attendant') and active = 1
  loop
    loop
      candidate := lpad(floor(random() * 10000)::integer::text, 4, '0');
      exit when not exists (select 1 from public.app_users where username = candidate);
    end loop;
    update public.app_users set username = candidate where id = operation_user.id;
  end loop;
end
$$;

create or replace function public.create_operation_code(
  p_code text,
  p_display_name text,
  p_role text,
  p_pin_salt text,
  p_pin_hash text,
  p_group_id bigint,
  p_start_date date,
  p_end_date date
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  created_user_id bigint;
begin
  if p_code !~ '^[0-9]{4}$' or p_role not in ('driver', 'attendant') or p_start_date > p_end_date then
    raise exception 'invalid operation code data';
  end if;

  if not exists (
    select 1 from public.inspection_groups
    where id = p_group_id and active = 1
  ) then
    raise exception 'inspection group not found';
  end if;

  insert into public.app_users (username, display_name, role, pin_salt, pin_hash, active)
  values (p_code, p_display_name, p_role, p_pin_salt, p_pin_hash, 1)
  returning id into created_user_id;

  insert into public.user_group_assignments (user_id, group_id, start_date, end_date)
  values (created_user_id, p_group_id, p_start_date, p_end_date);

  return created_user_id;
end;
$$;

create or replace function public.update_operation_code(
  p_user_id bigint,
  p_code text,
  p_display_name text,
  p_role text,
  p_group_id bigint,
  p_start_date date,
  p_end_date date
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if p_code !~ '^[0-9]{4}$' or p_role not in ('driver', 'attendant') or p_start_date > p_end_date then
    raise exception 'invalid operation code data';
  end if;

  if not exists (
    select 1 from public.inspection_groups
    where id = p_group_id and active = 1
  ) then
    raise exception 'inspection group not found';
  end if;

  update public.app_users
  set username = p_code,
      display_name = p_display_name,
      role = p_role
  where id = p_user_id
    and active = 1
    and role in ('driver', 'attendant');

  if not found then
    raise exception 'operation user not found';
  end if;

  insert into public.user_group_assignments (user_id, group_id, start_date, end_date)
  values (p_user_id, p_group_id, p_start_date, p_end_date)
  on conflict (user_id) do update
    set group_id = excluded.group_id,
        start_date = excluded.start_date,
        end_date = excluded.end_date;

  delete from public.sessions where user_id = p_user_id;
end;
$$;

create or replace function public.delete_operation_code(p_user_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.app_users
  set active = 0
  where id = p_user_id
    and active = 1
    and role in ('driver', 'attendant');

  if not found then
    raise exception 'operation user not found';
  end if;

  delete from public.user_group_assignments where user_id = p_user_id;
  delete from public.sessions where user_id = p_user_id;
end;
$$;

revoke all on function public.create_operation_code(text, text, text, text, text, bigint, date, date) from public, anon, authenticated;
revoke all on function public.update_operation_code(bigint, text, text, text, bigint, date, date) from public, anon, authenticated;
revoke all on function public.delete_operation_code(bigint) from public, anon, authenticated;
grant execute on function public.create_operation_code(text, text, text, text, text, bigint, date, date) to service_role;
grant execute on function public.update_operation_code(bigint, text, text, text, bigint, date, date) to service_role;
grant execute on function public.delete_operation_code(bigint) to service_role;
